/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/business-settings': RouteRecordInfo<
      '/admin/business-settings',
      '/admin/business-settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/categories': RouteRecordInfo<
      '/admin/categories',
      '/admin/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/modifier-groups': RouteRecordInfo<
      '/admin/modifier-groups',
      '/admin/modifier-groups',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/orders': RouteRecordInfo<
      '/admin/orders',
      '/admin/orders',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/Products': RouteRecordInfo<
      '/admin/Products',
      '/admin/Products',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/checkout': RouteRecordInfo<
      '/checkout',
      '/checkout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/menu': RouteRecordInfo<
      '/menu',
      '/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/order-status': RouteRecordInfo<
      '/order-status',
      '/order-status',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/order-success': RouteRecordInfo<
      '/order-success',
      '/order-success',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/processing': RouteRecordInfo<
      '/processing',
      '/processing',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/register': RouteRecordInfo<
      '/register',
      '/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/business-settings.vue': {
      routes:
        | '/admin/business-settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/categories.vue': {
      routes:
        | '/admin/categories'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/modifier-groups.vue': {
      routes:
        | '/admin/modifier-groups'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/orders.vue': {
      routes:
        | '/admin/orders'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/admin/Products.vue': {
      routes:
        | '/admin/Products'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/checkout.vue': {
      routes:
        | '/checkout'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/menu.vue': {
      routes:
        | '/menu'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/order-status.vue': {
      routes:
        | '/order-status'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/order-success.vue': {
      routes:
        | '/order-success'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/processing.vue': {
      routes:
        | '/processing'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/register.vue': {
      routes:
        | '/register'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
